server:
  port: 8001
  compression:
    enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  sendgrid:
    api-key: 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
  session:
    mongodb:
      collection-name: session
  graphql:
    graphiql:
      enabled: true
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      database: authenticate
      auto-index-creation: true
      uri: mongodb+srv://admin-gear:Supersadio2023@cluster0.1ect0pa.mongodb.net/authenticate?retryWrites=true&w=majority&appName=Cluster0

  mail:
    protocol: smtp
    host: smtp.gmail.com
    username: sendmailticket@gmail.com
    password: rilt nwxf vyqp flpd
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


auto-gear:
  api:
    version: v1
  security:
    TTLLoggedIn: 1
    MaxAttempt: 3

    allowList:
      - auth/allUser/**
      - auth/signup/**
      - auth/registerConfirm/**
    roleHierarchyHierarchy: ROLE_ADMIN > ROLE_USER

  clientConfiguration:
    urlAppClient: 192.168.190.36:3000/confirm-register

  redisConfiguration:
    type: alone
    host: localhost
    port: 6379
#    userName: default
#    password: O8Klin6WPMMaJfID9IBZEhsBIz6Pqozg

  cfConfiguration:
    region: auto
    accessKey: AKIATCKANO5TE77MZON3
    secretKey: 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
    accountId: 22bc2eb698766d70fb0ff8cdc8456e32
    bucketName: dev-media
    endPoint: https://22bc2eb698766d70fb0ff8cdc8456e32.r2.cloudflarestorage.com
  driveConfiguration:
    name: dev
  gpcConfiguration:
    projectId: manga-428613