
## @no-cookie-jar
POST http://localhost:8001/v1/api/auth/login
Content-Type: application/json
Cache-Control: no-cache

{ "email" : "aupv96@gmail.com", "password": "1234567" }


####
## @no-cookie-jar
#OPTIONS http://localhost:8001/v1/api/auth
#
#
####
#POST http://localhost:8001/v1/api/auth/signup/resendVerify
#Content-Type: application/json
#
#{ "email" : "aupv96@gmail.com" }
#
####
#GET http://localhost:8001/v1/api/auth/signup/confirm?token=Set-Cookie: user_session=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE3MDI4MDM2MTkyMzAsImlhdCI6MTcwMjgwMzYxOSwidXNlcklEIjoiMjNjMjA2N2ItNDk1Mi00NzhmLTlmOTYtM2YxNzFjY2M0YzhhIiwiZW1haWwiOiJhdXB2OTZAZ21haWwuY29tIn0.2rLZbMIRpUfT0pzlSzH08kIO2rCftmDkeoVPhgcyonRW2x6GjO5i0wMz1rCxQlRtYLrP5LZDh62C4c6Ua8dDlVl7HaAiGhyVcuTRYM-MDZAMrEeA_YRvHLRfzukmJLr6xlT7dxznVU2jrCKFCcfwY8Y-y6SehLDruhVv3cmQP6J6AZ9o2KMapBjGBSVoa5cStej5Puhjs7stpi_vc8OUz7-lb5ehvXpKjV7ZzO5ZRMHDIVv_rKP1pCJrCfs2HRK1w9qBtlFcB93bDvnYMmppPmY8N9a8o_QatuHdVGKh3nst-HaWz4qPASqCIW0dj-ttS63LExc3cA11JTPoUWMWjw
#Set-Cookie: logged_in=true
#Set-Cookie: _ag_sess=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE3MDI4MDM2MzQ2OTYsImlhdCI6MTcwMjgwMzYxOSwidXNlcklEIjoiMjNjMjA2N2ItNDk1Mi00NzhmLTlmOTYtM2YxNzFjY2M0YzhhIiwiZW1haWwiOiJhdXB2OTZAZ21haWwuY29tIn0.3SbkZjMvYxyNynTaoFpf8OFm8xv4J3fLSamTEEqbPQ0ths9-duYURnB792Q2PUPpbxw0PJ7oYdrKOxkn
#Accept: application/json
#
####
#DELETE http://localhost:8001/v1/api/auth/logout
#Cookie: user_session=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE3MDI4MTQ2ODA1NDEsImlhdCI6MTcwMjgxNDY4MCwidXNlcklEIjoiZjI2YzBlOGUtYmI0OC00OTFiLWI3ZTEtMjYyYjNlM2ZkYTdhIiwiZW1haWwiOiJhdXB2OTZAZ21haWwuY29tIn0.sbDOMy6238TfYN5kn8waz1IYrgjiOLHjbBLaSyTJrLtARn0RRZn3tN1hgizRiQ6vZ77R_gCFkVgfQ1Toyk0yUZVdW2nnbWq1tvBERG_VjiXo2nTKF3ntpQsCa4qxBpAwBc485Z85TtjZu8qjv5_5ag_piLYabrxIYwdbeGEoWMVYP-fOWwrGQrcKfxQMld71meLnnS0C1nmGMoMZNsZSmOxUrDgYryA6AZb1CX7VqareXz_FCiOK-S5DJ2raqMG3bw9EhJYv7xDj2NI26QHwaXmXwlsYQnSF06_JoQUwUUNuM8u9vHpYh-vgbWa7_DZ_ratIAPlNprp_fZDxIqPQoQ
#Cookie: _ag_sess=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE3MDI4MTQ2OTYwMDcsImlhdCI6MTcwMjgxNDY4MCwidXNlcklEIjoiZjI2YzBlOGUtYmI0OC00OTFiLWI3ZTEtMjYyYjNlM2ZkYTdhIiwiZW1haWwiOiJhdXB2OTZAZ21haWwuY29tIn0.jsMnGsL-aozOu4Vf3w5O3j42xvA0EdviM7cizBHI_hs-sOQMtErXYDdPYEZkZXLQKyWsK5pg6QTKWEZ9k_JwMoFuQIYk4STJxJ112lzCj2gwM64ztS3oBln7qbSG0O8WxYF4MlMuhq30tdrHsX01TA9wQYOCUbprIhleTVtDMxW7MxdvFDZ3DmghykkHcr5ZoHVn46q-BQEBDwolmuyZ12aBCLXaXfl9Q3CgQ0JJSCNIZRxLHrCaCpE36N6fjfrEk5ed_On3xsCL1nTcZBCgu3QAf_tAloAED4mo5VHE9NACgJfullBPT-H7TOE9CJopwCRtHCy6Q62QSzFDKIihrA
#
#
#
#
####
####
#POST http://localhost:8001/v1/api/users/c6481200-64cc-499e-bfaa-a028c558e5d7
#Content-Type: application/json
#Cookie: user_session=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE3MDI4ODk5MzMwMjYsImlhdCI6MTcwMjg4OTkzMiwidXNlcklEIjoiYzY0ODEyMDAtNjRjYy00OTllLWJmYWEtYTAyOGM1NThlNWQ3IiwiZW1haWwiOiJhdXB2OTZAZ21haWwuY29tIn0.LwPPxk871pDBYkSXpkr6flFWtuH7uByz9VC86SY7ntDFdsNfVTXjhuo34ZnKE8f9Ru4TPEt5PDYvrQsO22GngU_O4Of8osIP5r1brWc2mOefx_WJiXQGjJNO-swTidhUaYRJYxuiKrBfmNs_Um9jiHWbWoz1gbIFXa9tEaBasfJJHb8EIGhJ0AUnjYsY0hOdwIthxconwbvxANybkyWNh0KMmMKds0ysfyj7pnIQ78QG3ozeNwW0hpmzXxQAk7HJhCcA_0d1MqaiqLHVPfdgB1C0NIG1XHPXVWg_G2sLwuYlCLGdfDdvMoCQY9_5UrBZxcJIJIgx_7_vzVnpGwBdcw
#
#{
#  "password": "1234567",
#  "oldPassword": "123456"
#}



###
POST http://localhost:8001/v1/api/auth/refresh
#Cookie: _ag_sess=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE3MDI5Njk0NTc4ODcsImlhdCI6MTcwMjk2OTQ0MywidXNlcklEIjoiYzY0ODEyMDAtNjRjYy00OTllLWJmYWEtYTAyOGM1NThlNWQ3IiwiZW1haWwiOiJhdXB2OTZAZ21haWwuY29tIn0.P9txalj6yBS1wO4El-cVhWNmHEutiSA7ncIurZdBfuGV9Xd4OwCFgeQxAaTL7ImdxTWp7ivTQAA4P222IpnxZ_tge8X5Jgvh7GXfIIHZF0ZdXSDCVsyBC8amw6d1QZAp-W68YfABB7rWKXBgDTQxOIKoziPpaPG14RS5l_lQ5xtCF3CcjFRlyoJmpamMncxNkAJLoNDRebAP2lptZ5oDIzQBEpRRIGDbKEMN26Qfg-ctaK0Nfawxk2JHBBWomQvbxP5XIt-ghX2CeFP5Xg_HRP6Uoh0AJ0ybA5062qo4wYj09By2XSETLsiszS9F57zlCqZJBPSl8bXFvFsxevzjJw
#Cache-Control: no-cache

